owner: chillcicada
repo: status

sites:
  - name: Service - Blog
    url: https://chillcicada.com
  - name: Service - Img
    url: https://img.chillcicada.com
  - name: Service - WebDAV
    url: https://webdav.chillcicada.com
    expectedStatusCodes:
      - 401
  - name: Service - Prs
    url: https://prs.chillcicada.com

assignees:
  - chillcicada

status-website:
  cname: status.chillcicada.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "Status | ChillCicada"
  introMessage: This page uses **real-time** data from our [GitHub repository](https://github.com/chillcicada/status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/chillcicada/status
